### PR TITLE
Added possibility to use a custom font

### PR DESCRIPTION
**Pull request by ghost**
Added a new function which can specify the custom font to be used: with_font() - new() will still use DejaVu.

### CODE REVIEW

**Comment by ghost** [comment]
@rukai Any comment on this one?

**Comment by ghost** [comment]
Is there actually any interest? @rukai

**Comment by rukai** [comment]
Hi, sorry to just leave you with no reply.
I'm not using vulkano anymore and therefore am no longer maintaining this project.
From looking at your git history you have some contributions to vulkano and related projects so I'm happy to add you as an owner to https://crates.io/crates/vulkano_text and then you can maintain the crate. Alternatively I can hand the crate over to the vulkano project itself if the current maintainers are interested.

**Comment by ghost** [comment]
Sadly I dont have much interest in maintaining this project.

**Pull request closed without merging**
